version: 0.2

env:
  parameter-store:
    DB_PWD: DEV-RDS-ADMIN-PASSWORD

phases:

  install:
    runtime-version:
      docker: 18

  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - docker build -t pmu_dashboard --build-arg DB_HOST=pickmealup-dev.cvpqpiq5fzvi.eu-west-1.rds.amazonaws.com --build-arg DB_PORT=5510 --build-arg DB_DATABASE=pickmealup --build-arg DB_USERNAME=admin --build-arg DB_PASSWORD=$DB_PWD .
      - docker tag pmu_dashboard 948108788286.dkr.ecr.eu-west-1.amazonaws.com/pmu_dashboard
      - docker push 948108788286.dkr.ecr.eu-west-1.amazonaws.com/pmu_dashboard

  post_build:
    commands:
      - echo Build completed on `date`
