version: 0.2

phases:

  install:
    runtime-version:
      docker: 18

  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - docker build -t pmu_dashboard .
      - docker tag pmu_dashboard 513295654712.dkr.ecr.eu-west-1.amazonaws.com/pmu_dashboard
      - docker push 513295654712.dkr.ecr.eu-west-1.amazonaws.com/pmu_dashboard
  post_build:
    commands:
      - echo Build completed on `date`
