version: 0.2

env:
  parameter-store:
    DB_HOST: DEV-RDS-DB-HOST
    DB_PORT: DEV-RDS-DB-PORT
    DB_DATABASE: DEV-RDS-DB-DATABASE
    DB_USERNAME: DEV-RDS-DB-USERNAME
    DB_PWD: DEV-RDS-ADMIN-PASSWORD

phases:

  install:
    runtime-version:
      docker: 18

  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - docker build -t pmu_dashboard --build-arg DB_HOST=$DB_HOST --build-arg DB_PORT=$DB_PORT --build-arg DB_DATABASE=$DB_DATABASE --build-arg DB_USERNAME=$DB_USERNAME --build-arg DB_PASSWORD=$DB_PWD .
      - docker tag pmu_dashboard 948108788286.dkr.ecr.eu-west-1.amazonaws.com/pmu_dashboard
      - docker push 948108788286.dkr.ecr.eu-west-1.amazonaws.com/pmu_dashboard

  post_build:
    commands:
      - echo Build completed on `date`
