version: 0.2

env:
  parameter-store:
    DB_HOST: PROD-RDS-DB-HOST
    DB_PORT: DEV-RDS-DB-PORT
    DB_DATABASE: DEV-RDS-DB-DATABASE
    DB_USERNAME: DEV-RDS-DB-USERNAME
    DB_PWD: PROD-RDS-ADMIN-PASSWORD
    AWS_COGNITO_KEY: PROD-COGNITO-KEY
    AWS_COGNITO_SECRET: PROD-COGNITO-SECRET
    AWS_COGNITO_REGION: DEV-AWS-DEFAULT-REGION
    AWS_COGNITO_CLIENT_ID: PROD-COGNITO-CLIENT-ID
    AWS_COGNITO_USER_POOL_ID: PROD-COGNITO-USER-POOL-ID
    S3_ACCESS_KEY_ID: PROD-COGNITO-KEY
    S3_SECRET_ACCESS_KEY: PROD-COGNITO-SECRET
    S3_DEF_REGION: DEV-AWS-DEFAULT-REGION
    S3_BUCKET: DEV-AWS-BUCKET-IMAGES
    STRIPE_KEY: DEV-STRIPE-KEY
    STRIPE_SECRET: DEV-STRIPE-SECRET

phases:

  install:
    runtime-version:
      docker: 18

  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - docker build -t pmu_dashboard --build-arg DB_HOST=$DB_HOST --build-arg DB_PORT=$DB_PORT --build-arg DB_DATABASE=$DB_DATABASE --build-arg DB_USERNAME=$DB_USERNAME --build-arg DB_PASSWORD=$DB_PWD --build-arg AWS_COGNITO_KEY=$AWS_COGNITO_KEY --build-arg AWS_COGNITO_SECRET=$AWS_COGNITO_SECRET --build-arg AWS_COGNITO_REGION=$AWS_COGNITO_REGION --build-arg AWS_COGNITO_CLIENT_ID=$AWS_COGNITO_CLIENT_ID --build-arg AWS_COGNITO_USER_POOL_ID=$AWS_COGNITO_USER_POOL_ID --build-arg S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID --build-arg S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY --build-arg S3_DEF_REGION=$S3_DEF_REGION --build-arg S3_BUCKET=$S3_BUCKET --build-arg STRIPE_KEY=$STRIPE_KEY --build-arg STRIPE_SECRET=$STRIPE_SECRET .
      - docker tag pmu_dashboard 513295654712.dkr.ecr.eu-west-1.amazonaws.com/pmu_dashboard
      - docker push 513295654712.dkr.ecr.eu-west-1.amazonaws.com/pmu_dashboard
  post_build:
    commands:
      - echo Build completed on `date`
